export type {
  ApiErrorBody,
  ApiErrorCode,
  ApiErrorEnvelope,
  AuthSession,
  DatabaseStatus,
  HealthResponse,
  HealthStatus,
  ISODateTimeString,
  LoginPayload,
  PasswordChangePayload,
  PasswordResetConfirmPayload,
  PasswordResetRequestPayload,
  PasswordResetRequestedResponse,
  PermissionString,
  ProfileUpdatePayload,
  RefreshPayload,
  RegisterPayload,
  RootHealthResponse,
  SessionListResponse,
  TokenPair,
  User,
  UserDeletionPayload,
  UserRole,
  UUIDString,
} from './api'

export type { PageMeta, Paginated, PaginationParams } from './pagination'

export {
  ANALYTICS_CSV_DATASETS,
  ANALYTICS_TREND_METRICS,
  DEFAULT_WINDOW_PRESET,
  MAX_ANALYTICS_RANGE_DAYS,
  WINDOW_PRESETS,
  formatRangeLabel,
  isDateOnly,
  isWindowPreset,
  parseDateOnly,
  rangeDays,
  resolveWindow,
  shiftDays,
  toDateOnly,
  todayDateOnly,
} from './analytics'
export type {
  AnalyticsCsvDataset,
  AnalyticsListParams,
  AnalyticsRange,
  ComparisonTotal,
  ConsistencyRead,
  CsvExportManifestRead,
  DailyMetricRead,
  DeadlineAdherenceRead,
  EstimationAccuracyRead,
  FocusRead,
  Granularity,
  KnowledgeAnalyticsRead,
  LearningAnalyticsRead,
  MetricRange,
  OverdueTaskRead,
  OverviewRead,
  ProductivityRead,
  ProjectAnalyticsRead,
  RebuildRead,
  ScoreComponent,
  TagCount,
  TagCountRead,
  TaskAnalyticsRead,
  TimeBucketRead,
  TimeDistributionRead,
  TimeSlice,
  TrendMetric,
  TrendPoint,
  VelocityRead,
  WindowPreset,
  WindowPresetId,
  WorkloadRead,
} from './analytics'

export {
  KNOWLEDGE_ENTITY_META,
  KNOWLEDGE_ENTITY_TYPES,
  KNOWLEDGE_LINK_TYPES,
  LINK_TYPE_META,
  NOTE_STATUS_META,
  NOTE_STATUSES,
  RESOURCE_TYPES,
  RESOURCE_TYPE_META,
  formatKnowledgeDate,
  formatKnowledgeDateTime,
  formatRelative,
  renderMarkdown,
  summarise,
} from './knowledge'
export type {
  BacklinkParams,
  BacklinksResponse,
  Bookmark,
  BookmarkCreatePayload,
  BookmarkListParams,
  BookmarkUpdatePayload,
  CategoryCreatePayload,
  CategoryListParams,
  CategoryUpdatePayload,
  Concept,
  ConceptCreatePayload,
  ConceptListParams,
  ConceptUpdatePayload,
  Document,
  DocumentCreatePayload,
  DocumentListParams,
  DocumentUpdatePayload,
  GraphParams,
  KnowledgeCategory,
  KnowledgeEntityType,
  KnowledgeGraph,
  KnowledgeGraphEdge,
  KnowledgeGraphNode,
  KnowledgeLink,
  KnowledgeLinkCreatePayload,
  KnowledgeLinkType,
  KnowledgeSearchResult,
  Note,
  NoteCreatePayload,
  NoteListParams,
  NoteRevision,
  NoteStatus,
  NoteUpdatePayload,
  OutboundLinkParams,
  Resource,
  ResourceCreatePayload,
  ResourceListParams,
  ResourceType,
  ResourceUpdatePayload,
  SearchParams,
} from './knowledge'

export {
  CONFLICT_KIND_META,
  CONFLICT_SEVERITY_META,
  EVENT_TYPE_META,
  WEEKDAY_LABELS,
  WORK_SESSION_STATUS_META,
  formatPlannerInstant,
  formatPlannerMinutes,
  formatPlannerRatio,
} from './planner'
export type {
  AvailabilityReplacementPayload,
  AvailabilityRule,
  AvailabilityRuleInput,
  AvailabilityWeek,
  CalendarEvent,
  CalendarEventCreatePayload,
  CalendarEventListParams,
  CalendarEventType,
  CalendarEventUpdatePayload,
  Conflict,
  ConflictKind,
  ConflictList,
  ConflictListParams,
  ConflictSeverity,
  DateOnlyString,
  PlannerDay,
  PlannerListParams,
  PlannerMonth,
  PlannerSlot,
  PlannerSuggestion,
  PlannerView,
  PlannerWeek,
  PlannerWindow,
  SuggestionRequest,
  SuggestionResponse,
  WeekTotals,
  WorkSession,
  WorkSessionCreatePayload,
  WorkSessionListParams,
  WorkSessionStatus,
  WorkSessionUpdatePayload,
} from './planner'

export { PRIORITY_META, PROJECT_STATUS_META, TASK_STATUS_META, TASK_STATUS_ORDER } from './work'
export type {
  ActivityEvent,
  ActivityListParams,
  ActivityPage,
  ActivityStats,
  DateOnlyString as WorkDateOnlyString,
  Project,
  ProjectCreatePayload,
  ProjectListParams,
  ProjectPage,
  ProjectPriority,
  ProjectStats,
  ProjectStatus,
  ProjectSummary,
  ProjectTaskListParams,
  ProjectUpdatePayload,
  SortOrder,
  StatusMeta,
  StatusTone,
  TagAssignmentPayload,
  TagListParams,
  TagPage,
  Task,
  TaskCreatePayload,
  TaskListParams,
  TaskPage,
  TaskPriority,
  TaskStats,
  TaskStatus,
  TaskStatusChangePayload,
  TaskSummary,
  TaskUpdatePayload,
  WorkEventType,
  WorkTag,
} from './work'

// Phase 7. Re-exported like every other feature's types so consumers reach them
// from the barrel rather than importing `@/types/risk` directly — the risk
// vocabulary is a set of frozen arrays as well as derived types, so the
// constants are re-exported by value and the rest as types.
export {
  EVIDENCE_STRENGTHS,
  OPEN_RECOMMENDATION_STATUSES,
  RECOMMENDATION_PRIORITIES,
  RECOMMENDATION_STATUSES,
  RECOMMENDATION_TYPES,
  RISK_SEVERITIES,
  RISK_STATUSES,
  RISK_TYPES,
} from './risk'
export type {
  EvaluationListParams,
  EvaluationParams,
  EvaluationRead,
  EvidenceStrength,
  RecommendationListParams,
  RecommendationListRead,
  RecommendationPriority,
  RecommendationRead,
  RecommendationStatus,
  RecommendationSummaryRead,
  RecommendationType,
  RiskEvidenceRead,
  RiskListParams,
  RiskListRead,
  RiskRead,
  RiskSeverity,
  RiskStatus,
  RiskSummaryRead,
  RiskType,
} from './risk'

// Phase 8. Re-exported like every other feature's types so consumers reach them
// from the barrel rather than importing `@/types/developer` directly. The
// developer vocabulary is a set of frozen `as const` arrays plus a handful of
// mirrors of the server's configured defaults, so those go out by value and the
// rest as types. `PaginationParams` is deliberately absent from the type block:
// it already comes from './pagination', and exporting it twice collides.
export {
  ACTIVITY_GRANULARITIES,
  DEVELOPER_DEFAULT_ACTIVITY_GRANULARITY,
  DEVELOPER_DEFAULT_WINDOW_DAYS,
  DEVELOPER_FEATURE_SCHEMA_VERSIONS,
  DEVELOPER_METRIC_KEYS,
  DEVELOPER_METRIC_UNITS,
  GIT_SCAN_STATUSES,
  MAX_DEVELOPER_WINDOW_DAYS,
  NOT_ENOUGH_DATA,
} from './developer'
export type {
  ActivityGranularity,
  ActivityParams,
  BranchListRead,
  BranchRead,
  CommitListParams,
  CommitListRead,
  CommitRead,
  DeveloperActivityBucketRead,
  DeveloperActivityRead,
  DeveloperFeatureSchemaVersion,
  DeveloperFeatureValues,
  DeveloperFeatureVectorRead,
  DeveloperMetricKey,
  DeveloperMetricRead,
  DeveloperMetricUnit,
  DeveloperSummaryRead,
  DeveloperWindowParams,
  GitScanStatus,
  ProjectDeveloperRead,
  RepositoryCreatePayload,
  RepositoryFeatureVectorRead,
  RepositoryListParams,
  RepositoryListRead,
  RepositoryRead,
  RepositoryScanParams,
  RepositoryUpdatePayload,
  ScanRunRead,
} from './developer'

// Phase 9. Re-exported like every other feature's types so consumers reach them
// from the barrel rather than importing `@/types/learning` directly. The learning
// and career vocabulary is a set of frozen `as const` arrays plus mirrors of the
// server's configured defaults, so those go out by value and the rest as types.
// Four names are deliberately absent from the type block because the barrel
// already exports them from their own home — `PaginationParams` from
// './pagination', `ISODateTimeString` and `UUIDString` from './api', and
// `DateOnlyString` (as `WorkDateOnlyString`) plus `ProjectPriority` from
// './work'. `./learning` re-exports the first three itself, so naming any of
// them here would be a duplicate export of one symbol.
export {
  CAREER_EVIDENCE_TYPES,
  CAREER_FEATURE_SCHEMA_VERSIONS,
  CAREER_MAX_EVIDENCE,
  CAREER_RECORD_KINDS,
  CAREER_STALE_INACTIVE_DAYS,
  INSUFFICIENT_DATA_MESSAGE,
  LEARNING_ACTIVITY_TYPES,
  LEARNING_DEFAULT_WINDOW_DAYS,
  LEARNING_FEATURE_SCHEMA_VERSIONS,
  LEARNING_GOAL_STATUSES,
  LEARNING_MAX_GOALS,
  LEARNING_MAX_SKILLS,
  LEARNING_METRIC_UNITS,
  LEARNING_MIN_EVIDENCE_FOR_ESTIMATE,
  MAX_LEARNING_WINDOW_DAYS,
  MAX_SKILL_LEVEL,
  MIN_SKILL_LEVEL,
  SKILL_LEVEL_SOURCES,
} from './learning'
export type {
  CareerEvidenceCreatePayload,
  CareerEvidenceListParams,
  CareerEvidenceListRead,
  CareerEvidenceRead,
  CareerEvidenceType,
  CareerEvidenceUpdatePayload,
  CareerExperienceCreatePayload,
  CareerExperienceListParams,
  CareerExperienceListRead,
  CareerExperienceRead,
  CareerExperienceUpdatePayload,
  CareerFeatureSchemaVersion,
  CareerFeatureValues,
  CareerFeatureVectorRead,
  CareerProfileRead,
  CareerProfileUpsert,
  CareerRecordKind,
  CareerSummaryRead,
  LearningActivityBucketRead,
  LearningActivityCreatePayload,
  LearningActivityListParams,
  LearningActivityListRead,
  LearningActivityRead,
  LearningActivitySeriesRead,
  LearningActivityType,
  LearningFeatureSchemaVersion,
  LearningFeatureValues,
  LearningFeatureVectorRead,
  LearningGoalCreatePayload,
  LearningGoalListParams,
  LearningGoalListRead,
  LearningGoalRead,
  LearningGoalStatus,
  LearningGoalUpdatePayload,
  LearningMetricRead,
  LearningMetricUnit,
  LearningSummaryRead,
  LearningWindowParams,
  SkillCreatePayload,
  SkillGapListRead,
  SkillGapParams,
  SkillGapRead,
  SkillLevelSource,
  SkillListParams,
  SkillListRead,
  SkillRead,
  SkillUpdatePayload,
} from './learning'

export type {
  DestinationKind,
  IntentAlternative,
  IntentName,
  IntentRouteRead,
  MlStatusRead,
  ModelIdentityRead,
  RouteUtterancePayload,
  RoutingDecisionRead,
  RoutingStatus,
  ServiceTargetRead,
} from './ml'

// A value, so it cannot ride in the `export type` block above.
export { ROUTING_TIMEOUT_MS } from './ml'
